version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows

    environment:
      VERSION: "win10"
      HV: "N"
      BOOT_MODE: "windows_plain"

    volumes:
      - "/home/user/lwtram1/DockerShare:/storage/share"

    devices:
      - /dev/kvm

    cap_add:
      - NET_ADMIN

    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp

    stop_grace_period: 2m

    restart: on-failure
